package com.aura.music.data.stream

import com.aura.music.data.network.NetworkGate
import com.aura.music.data.prefs.PlaybackPreferences
import com.aura.music.data.recommendations.RadioPick
import com.aura.music.data.recommendations.RecommendationEngine
import com.aura.music.domain.repository.YouTubeTrack
import com.aura.music.playback.PlaybackController
import com.aura.music.playback.PlaybackUiState
import com.aura.music.playback.RepeatMode
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject
import javax.inject.Singleton

/** What the current queue is being filled from. */
private enum class SessionKind {
    /** No session: raw vault queue — radio engages at its tail. */
    NONE,
    /** A defined list (Saved / Downloads / continue-listening): plays in order. */
    PLAYLIST,
    /** Pure radio: every next song is an engine recommendation. */
    RADIO
}

/**
 * Answers "what plays next?" for every queue in the app.
 *
 * - **Playlist session** (Saved / Downloads / continue listening): the
 *   tapped track plays, then the list continues in order. At the list's
 *   dead end, radio takes over with engine recommendations — a playlist
 *   never terminates.
 * - **Radio session** (Top Hits / For You / Search / any single tap on a
 *   recommended song): the tapped track plays and *everything* after it is
 *   generated by [RecommendationEngine] — obsessions, replays, skips — not
 *   the list it was tapped from.
 * - **Spice-up** (Library switch): keeps [SPICE_AHEAD] engine picks queued
 *   behind playlist sessions too. Repeat modes still loop natively; radio
 *   only engages on repeat OFF.
 */
@Singleton
class UpNextManager @Inject constructor(
    private val controller: PlaybackController,
    private val transients: TransientTrackFactory,
    private val streamResolver: StreamResolver,
    private val engine: RecommendationEngine,
    private val prefs: PlaybackPreferences,
    private val gate: NetworkGate
) {
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)

    private val _events = MutableSharedFlow<String>(extraBufferCapacity = 2)
    val events: SharedFlow<String> = _events.asSharedFlow()

    val spiceUp: StateFlow<Boolean> = prefs.spiceUp
        .stateIn(scope, SharingStarted.Eagerly, false)

    fun toggleSpiceUp() {
        scope.launch { prefs.setSpiceUp(!spiceUp.value) }
    }

    private var kind: SessionKind = SessionKind.NONE
    private var origin: List<YouTubeTrack> = emptyList()
    private var generation = 0
    private var fillJob: Job? = null
    private var radioAnnounced = false
    private var radioExhausted = false
    private val radioPlayed = LinkedHashSet<String>()
    @Volatile private var fillBlockedUntil = 0L

    /** Song id the exhaust-retry latch was last armed for. */
    private var retryArmedForSongId: Long? = null

    init {
        scope.launch {
            controller.playbackState.collect { state -> maybeExtend(state) }
        }
    }

    /**
     * Begins (or replaces) a playlist session at [index] in [tracks]: the
     * list continues in order behind the tapped track, then radio at the end.
     */
    fun startPlaylistSession(tracks: List<YouTubeTrack>, index: Int) {
        generation++
        fillJob?.cancel()
        resetRadioMemory()
        kind = if (tracks.isEmpty()) SessionKind.NONE else SessionKind.PLAYLIST
        origin = tracks
        if (tracks.isEmpty()) return
        val g = generation
        val safeIndex = index.coerceIn(0, tracks.size - 1)
        fillJob = scope.launch {
            var appended = 0
            for (i in safeIndex + 1 until tracks.size) {
                if (appended >= PREFILL || g != generation) break
                try {
                    controller.addToQueueEnd(transients.fromTrack(tracks[i]))
                    appended++
                } catch (e: CancellationException) {
                    throw e
                } catch (_: Exception) {
                    // One unresolvable video must not stop the queue.
                }
            }
            // Warm whatever follows so later taps/skips stay instant.
            if (g == generation) {
                streamResolver.prefetch(
                    tracks.drop(safeIndex + 1 + appended).take(6).map { it.url }
                )
            }
        }
    }

    /**
     * Begins (or replaces) a radio session: whatever plays after the current
     * song comes from the recommendation engine, one pick after another,
     * indefinitely. Used for Top Hits, For You, and search taps.
     */
    fun startRadio() {
        generation++
        fillJob?.cancel()
        resetRadioMemory()
        kind = SessionKind.RADIO
        origin = emptyList()
    }

    /** Ends the session (e.g. user started a plain vault queue). */
    fun clear() {
        generation++
        fillJob?.cancel()
        kind = SessionKind.NONE
        origin = emptyList()
        resetRadioMemory()
    }

    private fun resetRadioMemory() {
        radioPlayed.clear()
        radioAnnounced = false
        radioExhausted = false
        retryArmedForSongId = null
        fillBlockedUntil = 0L
    }

    /**
     * Fires on every playback-state emission; all guards are cheap until
     * action is actually needed. [fillBlockedUntil] stops the 2/sec state
     * ticks from re-launching a fill that just concluded there is nothing
     * to append.
     */
    private fun maybeExtend(state: PlaybackUiState) {
        if (fillJob?.isActive == true) return
        if (System.currentTimeMillis() < fillBlockedUntil) return
        if (!gate.isAllowedNow()) return
        val queue = state.queue
        if (queue.isEmpty()) return
        val index = state.currentIndexInQueue
        if (index !in queue.indices) return

        // "Never terminates": every track change re-arms the search for picks
        // — a new current track means a new related graph to draw from, so a
        // previous "nothing found" is never final.
        val songId = state.currentSong?.id
        if (songId != retryArmedForSongId) {
            retryArmedForSongId = songId
            if (radioExhausted) {
                radioExhausted = false
                fillBlockedUntil = 0L
            }
        }

        val upcoming = queue.size - 1 - index
        val g = generation
        when (kind) {
            SessionKind.PLAYLIST -> when {
                upcoming <= 0 ->
                    fillJob = scope.launch { extendSession(queue, g) }
                // Spice-up pre-queues engine picks, but only once every
                // remaining origin item is already in the queue — playlist
                // order always wins over injected picks.
                spiceUp.value && upcoming < SPICE_AHEAD && originAllQueued(queue) ->
                    fillJob = scope.launch { appendRadio(queue, g, announce = false) }
            }
            // Radio session, or a raw vault queue: infinite recommendations.
            SessionKind.RADIO, SessionKind.NONE ->
                if (!radioExhausted && state.repeatMode == RepeatMode.OFF &&
                    (upcoming <= 0 || (spiceUp.value && upcoming < SPICE_AHEAD))
                ) {
                    fillJob = scope.launch {
                        appendRadio(queue, g, announce = upcoming <= 0)
                    }
                }
        }
    }

    /** True when no origin item is left to append before any spice pick. */
    private fun originAllQueued(queue: List<com.aura.music.data.db.SongEntity>): Boolean {
        val queuedUrls = queue.map { it.sourceUrl }.toSet()
        return origin.all { it.url in queuedUrls }
    }

    /** Blocks re-launch attempts until [ms] from now (called on Main). */
    private fun blockFillsFor(ms: Long) {
        fillBlockedUntil = System.currentTimeMillis() + ms
    }

    /** Continues a playlist session from its origin list; radio at the end. */
    private suspend fun extendSession(
        queue: List<com.aura.music.data.db.SongEntity>,
        g: Int
    ) {
        try {
            val queuedUrls = queue.map { it.sourceUrl }.toSet()
            val next = origin.firstOrNull { it.url !in queuedUrls }
                ?: run {
                    // Playlist dead end → radio recommendations take over.
                    appendRadio(queue, g, announce = true)
                    return
                }
            controller.addToQueueEnd(transients.fromTrack(next))
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            // Radio/extend is best-effort; playback of the current song continues.
            android.util.Log.w(TAG, "Session extend failed", e)
            if (g == generation) blockFillsFor(NOTHING_TO_APPEND_MS)
        }
    }

    /**
     * Appends one engine pick, skipping anything already queued or recently
     * radio-played. Vault-owned picks append as their local file — offline,
     * instant, no resolve step. Runs on Main (reads controller state, mutates
     * shared radio memory); the engine and stream resolver dispatch their own
     * heavy work.
     */
    private suspend fun appendRadio(
        queue: List<com.aura.music.data.db.SongEntity>,
        g: Int,
        announce: Boolean
    ) {
        if (radioExhausted) return
        val currentUrl = controller.playbackState.value.currentSong?.sourceUrl.orEmpty()
        val exclude = queue.map { it.sourceUrl }.toSet() + radioPlayed
        val picks = try {
            engine.radioPicks(currentUrl.ifBlank { null }, exclude, 1)
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            android.util.Log.w(TAG, "Radio pick failed", e)
            emptyList()
        }
        val pick = picks.firstOrNull()
        if (pick == null) {
            if (g == generation) {
                radioExhausted = true
                blockFillsFor(NOTHING_TO_APPEND_MS)
            }
            return
        }
        try {
            val song = when (pick) {
                is RadioPick.FromVault -> pick.song
                is RadioPick.FromStream -> transients.fromTrack(pick.track)
            }
            controller.addToQueueEnd(song)
            radioPlayed += pickUrl(pick)
            if (radioPlayed.size > 80) {
                val it = radioPlayed.iterator()
                if (it.hasNext()) {
                    it.next()
                    it.remove()
                }
            }
            if (announce && !radioAnnounced) {
                radioAnnounced = true
                _events.emit(RADIO_ANNOUNCEMENT)
            }
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            android.util.Log.w(TAG, "Radio append failed", e)
        }
    }

    private fun pickUrl(pick: RadioPick): String = when (pick) {
        is RadioPick.FromVault -> pick.song.sourceUrl
        is RadioPick.FromStream -> pick.track.url
    }

    companion object {
        private const val TAG = "UpNextManager"
        /** Resolved-and-queued ahead items per playlist session start. */
        const val PREFILL = 3
        /** Spice-up keeps this many songs queued behind the current one. */
        const val SPICE_AHEAD = 2
        /** Cooldown after a fill found nothing to append (state ticks at 2/sec). */
        const val NOTHING_TO_APPEND_MS = 15_000L
        const val RADIO_ANNOUNCEMENT = "Radio — recommendations from your listening"
    }
}
